export const mockChatHistory = [
  {
    id: 'alfjl2o38',
    title: 'Initial Chat History Session and Configuration Setup',
    description: 'Description 1',
    createdAt: '2021-01-01',
  },
  {
    id: 'fsajl23',
    title: 'Comprehensive Kubernetes Cluster Analysis and Resource Optimization',
    description: 'Analyzed pod resource usage and scaling recommendations',
    createdAt: '2024-09-15T14:30:00.000Z',
  },
  {
    id: 'k8s9x2m1',
    title: 'Advanced Debugging and Resolution of Memory Leak Issues',
    description: 'Investigated high memory consumption in production pods',
    createdAt: '2024-09-14T09:15:00.000Z',
  },
  {
    id: 'netpol4k9',
    title: 'Comprehensive Network Policy Configuration and Security Setup',
    description: 'Set up network policies for microservices communication',
    createdAt: '2024-09-13T16:45:00.000Z',
  },
  {
    id: 'helm5x7w',
    title: 'Advanced Helm Chart Deployment with Custom Value Configuration',
    description: 'Deployed application using Helm charts with custom values',
    createdAt: '2024-09-12T11:20:00.000Z',
  },
  {
    id: 'mon6y8z2',
    title: 'Comprehensive Monitoring Setup with Prometheus and Grafana Integration',
    description: 'Configured Prometheus and Grafana for cluster monitoring',
    createdAt: '2024-09-11T13:10:00.000Z',
  },
  {
    id: 'sec7a9b3',
    title: 'Comprehensive Security Audit and Vulnerability Assessment Analysis',
    description: 'Performed security scan and vulnerability assessment',
    createdAt: '2024-09-10T08:30:00.000Z',
  },
  {
    id: 'load8c0d4',
    title: 'Comprehensive Load Testing Results and Performance Analysis',
    description: 'Analyzed performance under high load conditions',
    createdAt: '2024-09-09T15:25:00.000Z',
  },
  {
    id: 'pod9e1f5',
    title: 'Advanced Pod Eviction Troubleshooting and Resource Constraint Resolution',
    description: 'Resolved pod eviction issues due to resource constraints',
    createdAt: '2024-09-08T10:45:00.000Z',
  },
  {
    id: 'mesh0g2h6',
    title: 'Comprehensive Service Mesh Configuration with Istio Integration',
    description: 'Set up Istio service mesh for microservices communication',
    createdAt: '2024-09-07T14:20:00.000Z',
  },
  {
    id: 'db1h3i7',
    title: 'Zero-Downtime Database Migration Strategy and Implementation Plan',
    description: 'Planned zero-downtime database migration for production',
    createdAt: '2024-09-06T16:30:00.000Z',
  },
  {
    id: 'cicd2i4j8',
    title: 'Advanced CI/CD Pipeline Optimization and Deployment Reliability Enhancement',
    description: 'Improved build times and deployment reliability',
    createdAt: '2024-09-05T11:15:00.000Z',
  },
  {
    id: 'reg3j5k9',
    title: 'Secure Container Registry Setup with Advanced Security Policies',
    description: 'Configured private container registry with security policies',
    createdAt: '2024-09-04T09:30:00.000Z',
  },
  {
    id: 'log4k6l0',
    title: 'Centralized Log Aggregation System with ELK Stack Implementation',
    description: 'Set up centralized logging with ELK stack',
    createdAt: '2024-09-03T13:45:00.000Z',
  },
  {
    id: 'back5l7m1',
    title: 'Comprehensive Backup and Disaster Recovery Plan Implementation',
    description: 'Implemented automated backup strategy for cluster data',
    createdAt: '2024-09-02T15:10:00.000Z',
  },
  {
    id: 'quot6m8n2',
    title: 'Advanced Resource Quotas Management and Namespace Configuration',
    description: 'Configured namespace resource quotas and limits',
    createdAt: '2024-09-01T12:25:00.000Z',
  },
  {
    id: 'dns7n9o3',
    title: 'Advanced DNS Troubleshooting and CoreDNS Configuration Resolution',
    description: 'Resolved CoreDNS configuration problems in cluster',
    createdAt: '2024-08-31T14:50:00.000Z',
  },
  {
    id: 'hpa8o0p4',
    title: 'Horizontal Pod Autoscaler Configuration and Metrics-Based Scaling',
    description: 'Configured HPA for automatic scaling based on metrics',
    createdAt: '2024-08-30T10:20:00.000Z',
  },
  {
    id: 'stor9p1q5',
    title: 'Advanced Storage Class Configuration with Dynamic Provisioning',
    description: 'Set up dynamic provisioning with persistent volumes',
    createdAt: '2024-08-29T16:35:00.000Z',
  },
  {
    id: 'api0q2r6',
    title: 'Comprehensive API Gateway Setup with Kong Integration',
    description: 'Implemented Kong API gateway for service management',
    createdAt: '2024-08-28T11:40:00.000Z',
  },
  {
    id: 'sec1r3s7',
    title: 'Advanced Secret Management Strategy with External Secrets Integration',
    description: 'Implemented secure secret management with external secrets',
    createdAt: '2024-08-27T13:15:00.000Z',
  },
  {
    id: 'upg2s4t8',
    title: 'Comprehensive Cluster Upgrade Planning and Version Migration Strategy',
    description: 'Planned rolling upgrade from v1.25 to v1.26',
    createdAt: '2024-08-26T15:30:00.000Z',
  },
  {
    id: 'multi3t5u9',
    title: 'Advanced Multi-tenant Architecture Design with Namespace Isolation',
    description: 'Designed namespace isolation for multiple teams',
    createdAt: '2024-08-25T09:45:00.000Z',
  },
  {
    id: 'dr4u6v0',
    title: 'Comprehensive Disaster Recovery Testing and Failover Procedures',
    description: 'Tested failover procedures and data recovery',
    createdAt: '2024-08-24T14:20:00.000Z',
  },
  {
    id: 'perf5v7w1',
    title: 'Advanced Performance Benchmarking and Load Testing Analysis',
    description: 'Conducted cluster performance tests under various loads',
    createdAt: '2024-08-23T12:10:00.000Z',
  },
  {
    id: 'git6w8x2',
    title: 'Comprehensive GitOps Workflow Setup with ArgoCD Integration',
    description: 'Implemented GitOps with ArgoCD for deployment automation',
    createdAt: '2024-08-22T16:55:00.000Z',
  },
  {
    id: 'scan7x9y3',
    title: 'Advanced Container Security Scanning and Vulnerability Assessment',
    description: 'Set up automated vulnerability scanning for container images',
    createdAt: '2024-08-21T10:30:00.000Z',
  },
  {
    id: 'crd8y0z4',
    title: 'Advanced Custom Resource Definitions and Application Configuration',
    description: 'Created CRDs for application-specific configurations',
    createdAt: '2024-08-20T13:25:00.000Z',
  },
  {
    id: 'net9z1a5',
    title: 'Advanced Network Segmentation and Security Isolation Implementation',
    description: 'Implemented network policies for security isolation',
    createdAt: '2024-08-19T15:40:00.000Z',
  },
  {
    id: 'alert0a2b6',
    title: 'Comprehensive Monitoring Alert Rules and Prometheus Configuration',
    description: 'Configured Prometheus alerting rules and thresholds',
    createdAt: '2024-08-18T11:15:00.000Z',
  },
  {
    id: 'pss1b3c7',
    title: 'Advanced Pod Security Standards Implementation and Security Enhancement',
    description: 'Implemented Pod Security Standards for enhanced security',
    createdAt: '2024-08-17T14:35:00.000Z',
  },
  {
    id: 'disc2c4d8',
    title: 'Advanced Service Discovery Optimization and Load Balancing Enhancement',
    description: 'Optimized service discovery and load balancing',
    createdAt: '2024-08-16T09:50:00.000Z',
  },
  {
    id: 'cost3d5e9',
    title: 'Comprehensive Cost Optimization Analysis and Resource Utilization Review',
    description: 'Analyzed cluster costs and resource utilization',
    createdAt: '2024-08-15T16:20:00.000Z',
  },
  {
    id: 'bg4e6f0',
    title: 'Advanced Blue-Green Deployment Strategy Implementation',
    description: 'Implemented blue-green deployment strategy',
    createdAt: '2024-08-14T12:45:00.000Z',
  },
  {
    id: 'can5f7g1',
    title: 'Comprehensive Canary Release Setup and Gradual Rollout Configuration',
    description: 'Configured canary deployment for gradual rollouts',
    createdAt: '2024-08-13T10:30:00.000Z',
  },
  {
    id: 'trace6g8h2',
    title: 'Advanced Distributed Tracing Setup with Jaeger Integration',
    description: 'Set up Jaeger for distributed tracing across services',
    createdAt: '2024-08-12T15:15:00.000Z',
  },
  {
    id: 'fed7h9i3',
    title: 'Advanced Cluster Federation Configuration for Global Deployment',
    description: 'Configured multi-cluster federation for global deployment',
    createdAt: '2024-08-11T13:40:00.000Z',
  },
  {
    id: 'dash8i0j4',
    title: 'Comprehensive Resource Monitoring Dashboard with Grafana Integration',
    description: 'Created Grafana dashboards for resource monitoring',
    createdAt: '2024-08-10T11:25:00.000Z',
  },
  {
    id: 'pdb9j1k5',
    title: 'Advanced Pod Disruption Budgets Configuration for High Availability',
    description: 'Configured PDBs for high availability during updates',
    createdAt: '2024-08-09T14:50:00.000Z',
  },
  {
    id: 'met0k2l6',
    title: 'Advanced Custom Metrics Collection and Prometheus Integration',
    description: 'Set up custom metrics collection with Prometheus',
    createdAt: '2024-08-08T16:10:00.000Z',
  },
  {
    id: 'test1l3m7',
    title: 'Comprehensive Network Policy Testing and Security Compliance Validation',
    description: 'Tested network policies for security compliance',
    createdAt: '2024-08-07T09:35:00.000Z',
  },
  {
    id: 'stor2m4n8',
    title: 'Advanced Storage Performance Tuning for Database Workloads',
    description: 'Optimized storage performance for database workloads',
    createdAt: '2024-08-06T12:20:00.000Z',
  },
  {
    id: 'mesh3n5o9',
    title: 'Advanced Service Mesh Security with mTLS and Istio Policies',
    description: 'Implemented mTLS and security policies in Istio',
    createdAt: '2024-08-05T15:45:00.000Z',
  },
  {
    id: 'cap4o6p0',
    title: 'Comprehensive Cluster Capacity Planning and Scaling Requirements Analysis',
    description: 'Analyzed cluster capacity and scaling requirements',
    createdAt: '2024-08-04T10:15:00.000Z',
  },
  {
    id: 'rate5p7q1',
    title: 'Advanced API Rate Limiting Implementation for Endpoint Protection',
    description: 'Implemented rate limiting for API endpoints',
    createdAt: '2024-08-03T13:30:00.000Z',
  },
  {
    id: 'life6q8r2',
    title: 'Advanced Pod Lifecycle Management and Graceful Shutdown Optimization',
    description: 'Optimized pod lifecycle and graceful shutdowns',
    createdAt: '2024-08-02T16:25:00.000Z',
  },
  {
    id: 'multi7r9s3',
    title: 'Comprehensive Multi-Region Deployment Strategy Implementation',
    description: 'Set up multi-region deployment strategy',
    createdAt: '2024-08-01T11:40:00.000Z',
  },
  {
    id: 'img8s0t4',
    title: 'Advanced Container Image Optimization for Size and Security Enhancement',
    description: 'Optimized container images for size and security',
    createdAt: '2024-07-31T14:55:00.000Z',
  },
  {
    id: 'dep9t1u5',
    title: 'Comprehensive Service Dependencies Mapping and Communication Analysis',
    description: 'Mapped service dependencies and communication patterns',
    createdAt: '2024-07-30T09:20:00.000Z',
  },
  {
    id: 'back0u2v6',
    title: 'Advanced Cluster Backup Strategy and Comprehensive Data Protection',
    description: 'Implemented comprehensive cluster backup solution',
    createdAt: '2024-07-29T15:10:00.000Z',
  },
  {
    id: 'quot1v3w7',
    title: 'Advanced Resource Quota Enforcement and Namespace Management',
    description: 'Enforced resource quotas across all namespaces',
    createdAt: '2024-07-28T12:35:00.000Z',
  },
  {
    id: 'ctx2w4x8',
    title: 'Advanced Pod Security Context Configuration and Isolation Setup',
    description: 'Configured security contexts for pod isolation',
    createdAt: '2024-07-27T16:45:00.000Z',
  },
  {
    id: 'net3x5y9',
    title: 'Advanced Network Performance Tuning and Latency Optimization',
    description: 'Optimized network performance and latency',
    createdAt: '2024-07-26T10:30:00.000Z',
  },
  {
    id: 'op4y6z0',
    title: 'Advanced Custom Operators Development for Application Management',
    description: 'Developed custom operators for application management',
    createdAt: '2024-07-25T13:15:00.000Z',
  },
  {
    id: 'obs5z7a1',
    title: 'Comprehensive Service Mesh Observability and Monitoring Setup',
    description: 'Set up observability tools for service mesh',
    createdAt: '2024-07-24T15:50:00.000Z',
  },
  {
    id: 'health6a8b2',
    title: 'Advanced Cluster Health Monitoring and Comprehensive System Analysis',
    description: 'Implemented comprehensive cluster health monitoring',
    createdAt: '2024-07-23T11:25:00.000Z',
  },
  {
    id: 'aff7b9c3',
    title: 'Advanced Pod Affinity Rules Configuration and Anti-Affinity Setup',
    description: 'Configured pod affinity and anti-affinity rules',
    createdAt: '2024-07-22T14:40:00.000Z',
  },
  {
    id: 'gw8c0d4',
    title: 'Advanced API Gateway Security and Policy Implementation',
    description: 'Implemented security policies in API gateway',
    createdAt: '2024-07-21T16:20:00.000Z',
  },
  {
    id: 'mig9d1e5',
    title: 'Advanced Storage Migration and Data Transfer Between Storage Classes',
    description: 'Migrated data between storage classes',
    createdAt: '2024-07-20T09:45:00.000Z',
  },
  {
    id: 'scale0e2f6',
    title: 'Comprehensive Cluster Scaling Strategy and Auto-Scaling Implementation',
    description: 'Implemented auto-scaling for cluster nodes',
    createdAt: '2024-07-19T12:30:00.000Z',
  },
  {
    id: 'traffic1f3g7',
    title: 'Advanced Service Mesh Traffic Management and Routing Configuration',
    description: 'Configured traffic splitting and routing rules',
    createdAt: '2024-07-18T15:15:00.000Z',
  },
  {
    id: 'res2g4h8',
    title: 'Advanced Pod Resource Optimization and Request/Limit Configuration',
    description: 'Optimized resource requests and limits for pods',
    createdAt: '2024-07-17T10:50:00.000Z',
  },
  {
    id: 'comp3h5i9',
    title: 'Comprehensive Network Policy Compliance and Namespace Validation',
    description: 'Ensured network policy compliance across namespaces',
    createdAt: '2024-07-16T13:35:00.000Z',
  },
  {
    id: 'dash4i6j0',
    title: 'Advanced Custom Metrics Dashboard and Grafana Integration',
    description: 'Created custom metrics dashboard in Grafana',
    createdAt: '2024-07-15T16:10:00.000Z',
  },
  {
    id: 'mig5j7k1',
    title: 'Advanced Pod Security Policy Migration to Security Standards',
    description: 'Migrated from PSP to Pod Security Standards',
    createdAt: '2024-07-14T11:20:00.000Z',
  },
  {
    id: 'troub6k8l2',
    title: 'Advanced Service Discovery Troubleshooting and Cluster Resolution',
    description: 'Resolved service discovery issues in cluster',
    createdAt: '2024-07-13T14:55:00.000Z',
  },
  {
    id: 'alloc7l9m3',
    title: 'Advanced Cluster Resource Allocation and Namespace Optimization',
    description: 'Optimized resource allocation across namespaces',
    createdAt: '2024-07-12T09:40:00.000Z',
  },
  {
    id: 'runtime8m0n4',
    title: 'Advanced Container Runtime Optimization and Performance Enhancement',
    description: 'Optimized container runtime performance',
    createdAt: '2024-07-11T12:25:00.000Z',
  },
  {
    id: 'lb9n1o5',
    title: 'API Gateway Load Balancing',
    description: 'Configured load balancing in API gateway',
    createdAt: '2024-07-10T15:30:00.000Z',
  },
  {
    id: 'health0o2p6',
    title: 'Pod Health Checks',
    description: 'Implemented comprehensive pod health checks',
    createdAt: '2024-07-09T10:15:00.000Z',
  },
  {
    id: 'seg1p3q7',
    title: 'Network Segmentation Testing',
    description: 'Tested network segmentation and isolation',
    createdAt: '2024-07-08T13:50:00.000Z',
  },
  {
    id: 'perf2q4r8',
    title: 'Storage Performance Monitoring',
    description: 'Set up storage performance monitoring',
    createdAt: '2024-07-07T16:35:00.000Z',
  },
  {
    id: 'pol3r5s9',
    title: 'Service Mesh Security Policies',
    description: 'Implemented security policies in service mesh',
    createdAt: '2024-07-06T11:45:00.000Z',
  },
  {
    id: 'test4s6t0',
    title: 'Cluster Backup Testing',
    description: 'Tested cluster backup and recovery procedures',
    createdAt: '2024-07-05T14:20:00.000Z',
  },
  {
    id: 'mon5t7u1',
    title: 'Pod Resource Monitoring',
    description: 'Set up pod resource usage monitoring',
    createdAt: '2024-07-04T09:30:00.000Z',
  },
  {
    id: 'opt6u8v2',
    title: 'Network Policy Optimization',
    description: 'Optimized network policies for better performance',
    createdAt: '2024-07-03T12:15:00.000Z',
  },
  {
    id: 'crm7v9w3',
    title: 'Custom Resource Monitoring',
    description: 'Set up monitoring for custom resources',
    createdAt: '2024-07-02T15:40:00.000Z',
  },
  {
    id: 'test8w0x4',
    title: 'Pod Security Context Testing',
    description: 'Tested pod security context configurations',
    createdAt: '2024-07-01T10:25:00.000Z',
  },
  {
    id: 'analysis9x1y5',
    title: 'Service Mesh Traffic Analysis',
    description: 'Analyzed service mesh traffic patterns',
    createdAt: '2024-06-30T13:10:00.000Z',
  },
  {
    id: 'clean0y2z6',
    title: 'Cluster Resource Cleanup',
    description: 'Cleaned up unused resources in cluster',
    createdAt: '2024-06-29T16:55:00.000Z',
  },
  {
    id: 'gw1z3a7',
    title: 'API Gateway Monitoring',
    description: 'Set up monitoring for API gateway performance',
    createdAt: '2024-06-28T11:30:00.000Z',
  },
  {
    id: 'life2a4b8',
    title: 'Pod Lifecycle Optimization',
    description: 'Optimized pod lifecycle management',
    createdAt: '2024-06-27T14:45:00.000Z',
  },
  {
    id: 'net3b5c9',
    title: 'Network Performance Analysis',
    description: 'Analyzed network performance bottlenecks',
    createdAt: '2024-06-26T09:20:00.000Z',
  },
  {
    id: 'stor4c6d0',
    title: 'Storage Class Optimization',
    description: 'Optimized storage class configurations',
    createdAt: '2024-06-25T12:35:00.000Z',
  },
  {
    id: 'review5d7e1',
    title: 'Service Mesh Configuration Review',
    description: 'Reviewed and optimized service mesh configuration',
    createdAt: '2024-06-24T15:50:00.000Z',
  },
  {
    id: 'alloc6e8f2',
    title: 'Pod Resource Allocation',
    description: 'Optimized pod resource allocation strategy',
    createdAt: '2024-06-23T10:15:00.000Z',
  },
  {
    id: 'review7f9g3',
    title: 'Network Policy Review',
    description: 'Reviewed and updated network policies',
    createdAt: '2024-06-22T13:40:00.000Z',
  },
  {
    id: 'audit8g0h4',
    title: 'Cluster Security Audit',
    description: 'Conducted comprehensive security audit',
    createdAt: '2024-06-21T16:25:00.000Z',
  },
  {
    id: 'health9h1i5',
    title: 'Pod Health Monitoring',
    description: 'Set up advanced pod health monitoring',
    createdAt: '2024-06-20T11:50:00.000Z',
  },
  {
    id: 'opt0i2j6',
    title: 'Service Discovery Optimization',
    description: 'Optimized service discovery performance',
    createdAt: '2024-06-19T14:30:00.000Z',
  },
  {
    id: 'img1j3k7',
    title: 'Container Image Security',
    description: 'Implemented container image security scanning',
    createdAt: '2024-06-18T09:45:00.000Z',
  },
  {
    id: 'aff2k4l8',
    title: 'Pod Affinity Optimization',
    description: 'Optimized pod affinity and anti-affinity rules',
    createdAt: '2024-06-17T12:20:00.000Z',
  },
  {
    id: 'seg3l5m9',
    title: 'Network Segmentation Review',
    description: 'Reviewed network segmentation strategy',
    createdAt: '2024-06-16T15:35:00.000Z',
  },
  {
    id: 'tune4m6n0',
    title: 'Storage Performance Tuning',
    description: 'Fine-tuned storage performance parameters',
    createdAt: '2024-06-15T10:10:00.000Z',
  },
  {
    id: 'mgmt5n7o1',
    title: 'Service Mesh Traffic Management',
    description: 'Optimized service mesh traffic management',
    createdAt: '2024-06-14T13:25:00.000Z',
  },
  {
    id: 'mon6o8p2',
    title: 'Pod Resource Monitoring',
    description: 'Enhanced pod resource monitoring capabilities',
    createdAt: '2024-06-13T16:40:00.000Z',
  },
  {
    id: 'test7p9q3',
    title: 'Network Policy Testing',
    description: 'Comprehensive network policy testing',
    createdAt: '2024-06-12T11:55:00.000Z',
  },
  {
    id: 'cap8q0r4',
    title: 'Cluster Capacity Analysis',
    description: 'Analyzed cluster capacity utilization',
    createdAt: '2024-06-11T14:15:00.000Z',
  },
  {
    id: 'pss9r1s5',
    title: 'Pod Security Standards Implementation',
    description: 'Implemented Pod Security Standards across cluster',
    createdAt: '2024-06-10T09:30:00.000Z',
  },
  {
    id: 'obs0s2t6',
    title: 'Service Mesh Observability Setup',
    description: 'Set up comprehensive service mesh observability',
    createdAt: '2024-06-09T12:45:00.000Z',
  },
  {
    id: 'runtime1t3u7',
    title: 'Container Runtime Security',
    description: 'Enhanced container runtime security measures',
    createdAt: '2024-06-08T15:20:00.000Z',
  },
  {
    id: 'life2u4v8',
    title: 'Pod Lifecycle Management',
    description: 'Improved pod lifecycle management processes',
    createdAt: '2024-06-07T10:35:00.000Z',
  },
  {
    id: 'perf3v5w9',
    title: 'Network Performance Optimization',
    description: 'Optimized network performance across cluster',
    createdAt: '2024-06-06T13:50:00.000Z',
  },
  {
    id: 'mgmt4w6x0',
    title: 'Storage Class Management',
    description: 'Improved storage class management strategy',
    createdAt: '2024-06-05T16:05:00.000Z',
  },
  {
    id: 'hard5x7y1',
    title: 'Service Mesh Security Hardening',
    description: 'Hardened security in service mesh configuration',
    createdAt: '2024-06-04T11:20:00.000Z',
  },
  {
    id: 'opt6y8z2',
    title: 'Pod Resource Optimization',
    description: 'Further optimized pod resource utilization',
    createdAt: '2024-06-03T14:35:00.000Z',
  },
  {
    id: 'comp7z9a3',
    title: 'Network Policy Compliance',
    description: 'Ensured full network policy compliance',
    createdAt: '2024-06-02T09:50:00.000Z',
  },
  {
    id: 'enh8a0b4',
    title: 'Cluster Monitoring Enhancement',
    description: 'Enhanced cluster monitoring capabilities',
    createdAt: '2024-06-01T12:15:00.000Z',
  },
];
